### ISSUE TITLE
Feature: Add MapIds Style Support

### ISSUE THREAD

**Issue by alexisk1** [ld0rman/google-maps-api-loader#10]
Google Maps JS supports custom map styling by using predefined MapIds through the google cloud console. Extend UrlBuilder to incorporate the feature.

**Comment by laurencedorman** [comment]
This library is deprecated.

**Comment by alexisk1** [comment]
@laurencedorman I don't mind contributing. I can do a PR if you are ok with it

**Comment by laurencedorman** [comment]
No, I'm not going to be publishing new versions of this library. It's completely redundant now there is [googlemaps/js-api-loader](https://github.com/googlemaps/js-api-loader)

**Comment by alexisk1** [comment]
Yes indeed you are right I will switch to the google maps js api loader package.
