### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by laurencedorman** [ld0rman/google-maps-api-loader#4]
Although functional, this code could be written in a much more flexible way to take into account future changes to Google's API. Also, it would be good to have it written in post ES5 JS.

**Comment by yankeeinlondon** [comment]
@laurencedorman would you consider a PR? I personally would like an ES6 export and typings for this library but i'm not sure I'm understanding your "flexibility" comment.

**Comment by laurencedorman** [comment]
Yep, happy to consider a PR. On flexibility I meant that any extra parameter that we need to pass to the Google Maps API should just be sent along in a `...rest`, so as to not have to open a Pull Request every time someone wants to send a new param.
