### ISSUE TITLE
New URL parameter in loader: map_ids

### ISSUE THREAD

**Issue by pp253** [ld0rman/google-maps-api-loader#9]
Hi,

Google has allowed the customization of the map using the tools in Google Cloud Platform.
To enable it, we have to add a new URL parameter in the loader: `map_ids`.
Would you consider to apply the new function? Thanks!

Ref:
https://developers.google.com/maps/documentation/javascript/styling

**Comment by laurencedorman** [comment]
I am deprecating this project, please use https://github.com/googlemaps/js-api-loader instead.
